### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by mkroening** [yannikschaelte/MiniPlaner#1]
Did you think about [choosing a license](https://choosealicense.com/)?

You don't have to, but right now the code is under exclusive copyright, so nobody except you can use it.

**Comment by yannikschaelte** [comment]
Thanks for the issue! I added the LGPL-3.0 now.

Thanks for your interest in the tool. If you are interested in using it in your software, I'd be happy to help (I know it's not overwhelmingly well documented ...).

Yannik

**Comment by mkroening** [comment]
Thanks for the quick answer!

In fact I have been developing a similar project for about two year now over at https://gitlab.com/altarplanner/altarplanner. I didn't dig into your codebase yet, but I think comparing approaches will be very interesting.
