### ISSUE TITLE
Tidy up build process

### ISSUE THREAD

**Issue by yannikschaelte** [yannikschaelte/MiniPlaner#27]
* [x] Build on Windows and Linux
* [x] Rewrite Makefile (or use alternative build) to be independent of system specifics
* [ ] Add Install.md
* [x] Support latest wxWidgets

**Comment by mkroening** [comment]
Sounds awesome! I can help with testing and packaging for Arch Linux.

If you are undecided about a build system jet, I would like to throw [The Meson Build System](https://mesonbuild.com/) in for consideration.

Edit: Oh, sorry. I already mentioned Meson in #6.

**Comment by mkroening** [comment]
Is this resolved by #6?

**Comment by yannikschaelte** [comment]
right. we should move the installation guide to an INSTALL.md file (following github standards), all else is nicely done.

**Comment by mkroening** [comment]
You mean basically the whole README?

GitHub suggests installation as aspect of the README: [Documenting your projects on GitHub · GitHub Guides](https://guides.github.com/features/wikis/#Formatting-a-readme)

**Comment by yannikschaelte** [comment]
I'll make a suggestion.

**Comment by mkroening** [comment]
So this was resolved in #43, right?
