### ISSUE TITLE
Change set develop as default branch

### ISSUE THREAD

**Issue by mkroening** [yannikschaelte/MiniPlaner#30]
Since `develop` is the branch reflects a state with the latest delivered development changes, it should be the default branch. That way it is the default target for comparisons and Pull requests.

It is done this way in [nvie/gitflow](https://github.com/nvie/gitflow), which should be a good reference in this regard.

What do you think?

**Comment by janochsner** [comment]
Finally got the time to set up my IDE and hope to work on this project soon as well...
Having "develop" as default would be great for that.

**Comment by yannikschaelte** [comment]
Hi, in our projects we usually keep the master as default branch, since it reflects the current release version and thus the main entry point for users. This has the disadvantage that pull request targets have to be adjusted always to develop manually. GitHub is not very forthcoming in that regard yet ... For the moment, I would leave it like that and then see how it develops. Is that fine?

**Comment by yannikschaelte** [comment]
By the way, I have sent you two invite links to work on the project. That should make some things easier.  Thanks again for your contributions already. :+1: 

In the current quarantine, I unfortunately have no access to the computer where my old development files for the MiniPlaner are lying, I will have to see to set things up on a different machine, hopefully soon. :crossed_fingers:

**Comment by mkroening** [comment]
> keep the master as default branch, since it reflects the current release version and thus the main entry point for users

That makes sense as long as you target users with this repository. I am used to targeting developers with these repositories, for whom it would make sense to have `develop` as default, and having the [GitHub Page](https://yannikschaelte.github.io/MiniPlaner/) for users, since they should not have to deal with the code in the repository, but I would be okay with leaving it as is. Currently, it's just a minor inconvenience.

**Comment by yannikschaelte** [comment]
On second thoughts, I agree here, with the changes discussed in #34. I will set the default to `develop` soon.

**Comment by yannikschaelte** [comment]
Then, should we close open issues also as soon as they are in develop? Policy with former setup is to close them as soon as they are in master, thus allowing users to see what is already/still open.

**Comment by mkroening** [comment]
I was not really familiar with that concept of having a `develop` branch before, but the blog post [1] does not mention issues explicitly. I think it would make sense to close the issues as soon as they are fixed in `develop`. People with the similar problems are still able to find closed issues and comment.

Anyways it would make sense to not wait long with pushing a new release for fixes.

[1] [A successful Git branching model » nvie.com](https://nvie.com/posts/a-successful-git-branching-model/)
