### ISSUE TITLE
Softcode AboutPanel

### ISSUE THREAD

**Issue by mkroening** [yannikschaelte/MiniPlaner#33]
Currently, all properties shown in the "About" panel are hard coded like this:
https://github.com/yannikschaelte/MiniPlaner/blob/01b5ccd792082d65c25e30e652f635b06666850e/src/view/AboutPanel.cpp#L52-L54

I am going to have a look at soft coding those entries once we have a working build system in place.

**Comment by yannikschaelte** [comment]
In the course, one can also add fields for "lead developer" and "developers/contributors", if that sounds right for you (as well as on github) ;)

**Comment by mkroening** [comment]
Oh, thanks! I'll add one then. :)
