### ISSUE TITLE
Separate Repository from Website

### ISSUE THREAD

**Issue by mkroening** [yannikschaelte/MiniPlaner#34]
I think we should separate the user experience from the developer experience.

Currently, [yannikschaelte.github.io/MiniPlaner](https://yannikschaelte.github.io/MiniPlaner) is generated from `master`. We can use a `gh-pages` branch for the website [1] and generate the website via an `index.md` file [2].

That way we can rewrite `README.md` to house relevant information about building the program, which are irrelevant to the end user and preferably written in English.

Furthermore, we should exclude binaries from the source tree. Things currently listed in "Download" and "Beispiel" in `README.md` should be added to the corresponding release: [MiniPlaner/v2.0.4](https://github.com/yannikschaelte/MiniPlaner/releases/tag/v2.0.4)

@yannikschaelte, what do you think?

[1] [Configuring a publishing source for your GitHub Pages site - GitHub Help](https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source)
[2] [Creating a GitHub Pages site - GitHub Help](https://help.github.com/en/github/working-with-github-pages/creating-a-github-pages-site#creating-your-site)

**Comment by yannikschaelte** [comment]
I fully agree here. Distributing binaries via releases definitely makes more sense, here they were just uploaded as part of the repo in the first place, but that was admittedly not super tidy.

**Comment by mkroening** [comment]
I don't have the necessary rights to change the branch, the website is being generated from. @yannikschaelte, could you take care of this?

I edited the [2.0.4](https://github.com/yannikschaelte/MiniPlaner/releases/tag/v2.0.4) release to contain the binaries. I omitted the 7z variants of the archives, is that okay?

Once the website is based of the new branch, we can provide the downloads via the releases section instead of the repository itself.

**Comment by yannikschaelte** [comment]
changed pages source to gh-pages. It is totally fine to omit the 7z archives.

**Comment by yannikschaelte** [comment]
Should now be online on https://yannikschaelte.github.io/MiniPlaner. I also changed the download targets to the release. Anything missing?
