### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by mkroening** [yannikschaelte/MiniPlaner#40]
I'll try to set up CI via GitHub actions now that #6 is merged.

**Comment by yannikschaelte** [comment]
What would be your goals in CI? There are no tests yet. Tests can then of course be added as new functionality comes in. 
Useful would be performing a full build, once on some linux system with standard gcc, and once on Windows. The latter may be more challenging. Automatic deployment (see #29) may also be of interest, however currently not pressing, given that the release cycle will probably not be too frequent.

**Comment by mkroening** [comment]
I'll just tackle compilation for the moment. Setting up MSYS2 here should work in principle.
