### ISSUE TITLE
Custom colors look inconsistent

### ISSUE THREAD

**Issue by mkroening** [yannikschaelte/MiniPlaner#47]
The program uses custom colors (hand-picked for windows) for several elements rendering the look and feel very inconsistent with the Adwaita theme:
![Screenshot from 2020-04-25 19-59-56](https://user-images.githubusercontent.com/28776973/80287404-bc44e380-8731-11ea-8a7e-ad8bd1e45abd.png)

It's even worse with the Adwaita dark theme:
![Screenshot from 2020-04-25 20-17-16](https://user-images.githubusercontent.com/28776973/80287414-c830a580-8731-11ea-8c21-e07fc30677dc.png)

It worked well removing the custom colors on some of them but I'll have to find all of them and verify that there are no regressions on Windows.

**Comment by yannikschaelte** [comment]
I see the point :)
